logging:
    file:
        name: app.log
server:
    port: 9000
spring:
    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        driver-class-name: ${DRIVER_CLASS_NAME}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
